#!/usr/bin/env zsh
bindkey -v

autoload -Uz compinit && compinit -i
zstyle ':completion:*' menu select=2
zmodload zsh/complist

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

PROMPT='%F{blue} %~ %f '

alias ls="ls --color=auto"
alias ll="ls -la"
